name: .NET Build + Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      CONFIGURATION: Release
      PROJECT_PATH: TextmapParser/TextmapParser.csproj
      OUTPUT_PATH: out

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Display .NET information
        run: dotnet --info

      - name: Restore
        run: dotnet restore TextmapParser.sln

      - name: Build
        run: >
          dotnet build AceMetaUnpack.sln
          --configuration ${{ env.CONFIGURATION }}
          --no-restore

      - name: Publish Windows x64
        run: >
          dotnet publish ${{ env.PROJECT_PATH }}
          --configuration ${{ env.CONFIGURATION }}
          --runtime win-x64
          --self-contained true
          -p:PublishSingleFile=true
          --output ${{ env.OUTPUT_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AceMetaUnpack-win-x64
          path: ${{ env.OUTPUT_PATH }}
          if-no-files-found: error
